### ISSUE TITLE
Retrieve EXIF File Meta Data?

### ISSUE THREAD

**Issue by confile** [bgrins/filereader.js#13]
I use your filereader but how can I get the EXIF meta data of the file in the load(e, file) {} function?

**Comment by bgrins** [comment]
I think there may be ways specific to file format.  For instance, http://blog.nihilogic.dk/2008/05/reading-exif-data-with-javascript.html.  I think you will just have to determine the type of file, then read its data and parse out the exif based on what type it is.  I don't know of anything that will do this automatically.  Would be very interesting to see a demo if you were able to get something working though.

**Comment by drmichaelgorski** [comment]
thank you
