### ISSUE TITLE
readAsBinaryString deprecated

### ISSUE THREAD

**Issue by ebi** [bgrins/filereader.js#17]
The `readAsBinaryString` method has been deprecated from the standard and apparently Microsoft removed it from IE10+.

**Comment by bgrins** [comment]
Ah, thanks for the info.  The spec agrees: http://dev.w3.org/2006/webapi/FileAPI/#reading-a-file.  So we need to remove it from the docs and choose a new default read method.   Probably data URL or array buffer.

**Comment by bgrins** [comment]
OK, I've removed `readAsBinaryString` from the docs and made the default `readAsDataURL`

**Comment by ebi** [comment]
Thank you
