### ISSUE TITLE
Only executes the second time

### ISSUE THREAD

**Issue by miltonmagalhaes** [bgrins/filereader.js#18]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>

<script src="http://www.jurisweb.adv.br/_js/jquery.js" language="javascript" type="text/javascript" charset="utf-8"></script>

<script src="http://www.jurisweb.adv.br/_js/jqueryFileReader.js" language="javascript" type="text/javascript" charset="utf-8"></script>

<script>
    $(document).ready(function()
        {
             if ($.browser.msie) {
                  $('#input').replaceWith($('#input').clone());
             } else {
                  $('#input').val('');
             }
        }
        );
</script>

<script>
var PdfA;
function LeArquivo(Arquivos)
    {
        alert($('#input').val());
        FileReaderJS.setSync(true);
        // Accept files from the specified input[type=file]
        FileReaderJS.setupInput(document.getElementById('input'), {
          readAsDefault: "Text",
          on: {
                    load: function(e, file) {
                                                console.log("Funcionou--->" + e.target.result.substring(1,8));
                                                PdfA = e.target.result.substring(1,8);
                                                if (PdfA != "PDF-1.4"){
                                                                        console.log("Não é PDF1;4");
                                                                        return false
                                                                    }
                                            }
                }
            
        });

    }
</script>

</head>

<body>
<input type="file" multiple id="input" onchange='LeArquivo(this.files)'>
</body>
</html>

**Comment by bgrins** [comment]
Can you provide a test case and more information about how to reproduce the problem?

**Comment by miltonmagalhaes** [comment]
this is the example.

<script>
var PdfA;
function LeArquivo(Arquivos)
    {
        alert($('#input').val());
        FileReaderJS.setSync(true);
        FileReaderJS.setupInput(document.getElementById('input'), {
         readAsDefault: "Text",
          on: {
                    load: function(e, file) {
                                                console.log("Funcionou--->" + e.target.result.substring(1,8));
                                                PdfA = e.target.result.substring(1,8);
                                                if (PdfA != "PDF-1.4"){
                                                                        console.log("Não é PDF1;4");
                                                                        return false
                                                                    }
                                            }
                }   
        });
    }
</script>

**Comment by bgrins** [comment]
> this is the example.

I don't understand - I just see a doctype in your initial comment

**Comment by miltonmagalhaes** [comment]
Brian

The code of filereader.js execute only the second time.
In the first time don't execute.

Date: Sat, 10 Jan 2015 18:29:03 -0800

**Comment by bgrins** [comment]
I don't see this problem on https://bgrins.github.io/filereader.js/.  Can you provide a test case (like on jsfiddle) that demonstrates this problem?  The description of the problem is not clear, and provides no additional steps to reproduce it.

**Comment by miltonmagalhaes** [comment]
http://jsfiddle.net/h3e0dgt8/

Date: Mon, 12 Jan 2015 08:46:11 -0800

**Comment by bgrins** [comment]
You need to call FileReaderJS.setupInput immediately and only once (before waiting for the onchange event on the input).

So call `FileReaderJS.setupInput` in DOM ready, then it should work as you are wanting.

**Comment by miltonmagalhaes** [comment]
You can send me a example

Date: Mon, 12 Jan 2015 10:36:54 -0800

**Comment by bgrins** [comment]
This example is linked to from the home page and should work how you are expecting: http://jsfiddle.net/bgrins/nWP59/.  All you should have to do is switch `setupDrop` to `setupInput`.

**Comment by miltonmagalhaes** [comment]
You don't undestand. I need a example about your comment:

You need to call FileReaderJS.setupInput immediately and only once (before waiting for the onchange event on the input).

So call FileReaderJS.setupInput in DOM ready, then it should work as you are wanting.

Date: Mon, 12 Jan 2015 10:57:33 -0800

**Comment by bgrins** [comment]
The example I sent is exactly what you will need to do, it just needs a very minor change (add an `<input type="file" />` to the page and change the call from `setupDrop` to `setupInput`)

**Comment by miltonmagalhaes** [comment]
Sorry, but don't work
See.

   I'm sorry, but does not work the only example replacing.
 My problem:
 Read more from PDF files and identify if they were generated in version 1.4.
 Each reading should return true or false.
 For example:
 if (IsFilePdf14 (File [i])) {} else {}
alert: I run in Firefox

Date: Mon, 12 Jan 2015 11:51:25 -0800
