### ISSUE TITLE
No access to FileReader.result within loadend callback

### ISSUE THREAD

**Issue by michaelcrain** [bgrins/filereader.js#22]
When "readAsArraybuffer", in order to get access to the arraybuffer in "reader.result" I had to pass the FileReader instance as the 3rd argument to the "opts" callback on line 346.

**Comment by michaelcrain** [comment]
Solved:  My oversight. The arraybuffer is attached to event.target, the first parameter passed to the onloadend callback.

**Comment by bgrins** [comment]
Alright, no problem
